apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: whoami-demo
  template:
    metadata:
      labels:
        app: whoami-demo
    spec:
      containers:
      - image: https://registry.k3s.cluster/whoami:latest
        name: whoami-demo
        ports:
        - containerPort: 80
