apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: whoami-demo
  template:
    metadata:
      labels:
        app: whoami-demo
    spec:
      containers:
      - image: registry.k3s.cluster/whoami:latest
        name: whoami-demo
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: whoami-demo
  namespace: new-dev
  labels:
    app: registry
spec:
  selector:
    app: whoami-demo
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-whoami-tls-ingress
  namespace: new-dev
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: my-ca-issuer
spec:
  rules:
    - host: new-whoami.k3s.cluster
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami-demo
                port:
                  number: 80
  tls:
    - secretName: new-whoami-tls-my-ca
      hosts:
        - new-whoami.k3s.cluster
